# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-21 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-postTime']},
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='postTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
