# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-21 03:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='draft',
        ),
    ]
