# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-25 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='genre',
            field=models.CharField(blank=True, choices=[('TE', 'Technology'), ('SC', 'Science'), ('HE', 'Health'), ('ED', 'Education'), ('EN', 'Entertainment'), ('SP', 'Sports'), ('BU', 'Business')], max_length=2),
        ),
    ]
