# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-25 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20171125_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='genre',
            field=models.CharField(choices=[('TE', 'Technology'), ('SC', 'Science'), ('HE', 'Health'), ('ED', 'Education'), ('EN', 'Entertainment'), ('SP', 'Sports'), ('BU', 'Business'), ('UK', 'General')], default='UK', max_length=2),
        ),
    ]
