# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-09 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20171125_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='rating',
            field=models.BigIntegerField(default=0),
        ),
    ]
