# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 02:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0011_likedislike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedislike',
            name='articleid',
        ),
        migrations.RemoveField(
            model_name='likedislike',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='article',
            name='rating',
        ),
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='LikeDislike',
        ),
    ]
