# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-22 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='articleid',
            new_name='article',
        ),
    ]
