# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-22 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20171122_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='datetime',
            new_name='dateTime',
        ),
    ]
